from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np
from etils import epath

from unilab.assets import ASSETS_ROOT_PATH
from unilab.base import registry
from unilab.base.backend import create_backend
from unilab.base.dtype_config import get_global_dtype
from unilab.base.np_env import NpEnvState
from unilab.envs.manipulation.inhand_rot_allegro.base import AllegroBaseCfg, AllegroBaseMjEnv
from unilab.utils.math_utils import np_quat_conjugate, np_quat_mul, np_quat_to_axis_angle

# ─────────────────────────── Configuration ────────────────────────────


@dataclass
class RewardConfig:
    scales: dict[str, float]
    # Rotation reward clipped to [angvel_clip_min, angvel_clip_max] rad/s
    angvel_clip_min: float
    angvel_clip_max: float
    # Object drops below this world-z → episode terminates.
    reset_z_threshold: float  # metres


@dataclass
class DomainRandConfig:
    # Small random perturbation added to each joint at reset (rad).
    joint_noise: float = 0.00
    # Random linear velocity injected into ball at reset (m/s).
    ball_vel_noise: float = 0.00
    # Z-offset added to ball position at reset (m).
    ball_z_offset: float = 0.0


@registry.envcfg("AllegroInhandRotation")
@dataclass
class AllegroRotationCfg(AllegroBaseCfg):
    model_file: str = str(ASSETS_ROOT_PATH / "robots" / "allegro_hand" / "scene.xml")
    max_episode_seconds: float = 20.0  # same as HORA
    reward_config: RewardConfig | None = None
    domain_rand: DomainRandConfig = field(default_factory=DomainRandConfig)

    # World-frame unit vector around which to reward rotation.
    # Default (+z) = counterclockwise when viewed from above.
    rotation_axis: tuple = (0.0, 0.0, 1.0)

    # Path to a grasp cache (.npy) generated by pre_grasp.py.
    # Empty string = auto-detect grasps/grasp_50k.npy beside this file.
    grasp_cache_path: str = ""

    # If True, disable grasp cache loading (for grasp generation mode).
    gen_grasp: bool = False


# ─────────────────────────── Environment ──────────────────────────────


@registry.env("AllegroInhandRotation", sim_backend="mujoco")
class AllegroRotationMj(AllegroBaseMjEnv):
    _cfg: AllegroRotationCfg
    _reward_cfg: RewardConfig

    def __init__(self, cfg: AllegroRotationCfg, num_envs: int = 1, backend_type: str = "mujoco"):
        if cfg.reward_config is None:
            raise ValueError("reward_config must be provided via Hydra configuration")
        backend = create_backend(backend_type, cfg.model_file, num_envs, cfg.sim_dt)
        super().__init__(cfg, backend, num_envs)
        self._enable_reward_log = True
        self._reward_cfg = cfg.reward_config

        # Normalisation constants for joint-position observation.
        self._dof_range = self._ctrl_upper - self._ctrl_lower  # (16,)
        self._dof_mid = (self._ctrl_upper + self._ctrl_lower) / 2.0  # (16,)

        # Rotation axis as a broadcast-ready (3,) unit vector.
        axis = np.array(cfg.rotation_axis, dtype=get_global_dtype())
        self._rot_axis = axis / np.linalg.norm(axis)

        # Grasp cache loaded lazily on first reset
        self._grasp_cache: np.ndarray | None = None
        self._grasp_cache_loaded = False

        self._init_reward_functions()
        self._init_domain_randomization("allegro_rotation")

    # ── Spaces ──────────────────────────────────────────────────────

    _NUM_OBS_PER_STEP = 35  # dof_pos_norm(16) + targets(16) + ball_pos(3)
    _NUM_LAG_STEPS = 3

    @property
    def obs_groups_spec(self) -> dict[str, int]:
        return {"obs": self._NUM_OBS_PER_STEP * self._NUM_LAG_STEPS}

    # ── Reward functions ─────────────────────────────────────────────

    def _init_reward_functions(self):
        self._reward_fns = {
            "rotate": self._reward_rotate,
            "obj_linvel": self._reward_obj_linvel,
            "pose_diff": self._reward_pose_diff,
            "torque": self._reward_torque,
            "work": self._reward_work,
            "drop": self._reward_drop,
        }

    def _reward_rotate(
        self, info, dof_pos, dof_vel, ball_pos, ball_linvel, ball_angvel, torques, terminated
    ) -> np.ndarray:
        vec_dot = ball_angvel @ self._rot_axis  # (N,)
        return np.asarray(
            np.clip(vec_dot, self._reward_cfg.angvel_clip_min, self._reward_cfg.angvel_clip_max)
        )

    def _reward_obj_linvel(
        self, info, dof_pos, dof_vel, ball_pos, ball_linvel, ball_angvel, torques, terminated
    ) -> np.ndarray:
        return np.asarray(np.sum(np.abs(ball_linvel), axis=1))

    def _reward_pose_diff(
        self, info, dof_pos, dof_vel, ball_pos, ball_linvel, ball_angvel, torques, terminated
    ) -> np.ndarray:
        diff = dof_pos - info["init_pose"]  # (N, 16)
        return np.asarray(np.sum(np.square(diff), axis=1))

    def _reward_torque(
        self, info, dof_pos, dof_vel, ball_pos, ball_linvel, ball_angvel, torques, terminated
    ) -> np.ndarray:
        return np.asarray(np.sum(np.square(torques), axis=1))

    def _reward_work(
        self, info, dof_pos, dof_vel, ball_pos, ball_linvel, ball_angvel, torques, terminated
    ) -> np.ndarray:
        work = np.sum(torques * dof_vel, axis=1)
        return np.asarray(np.square(work))

    def _reward_drop(
        self, info, dof_pos, dof_vel, ball_pos, ball_linvel, ball_angvel, torques, terminated
    ) -> np.ndarray:
        return np.asarray(terminated, dtype=get_global_dtype())

    # ── Core update pipeline ─────────────────────────────────────────

    def update_state(self, state: NpEnvState) -> NpEnvState:
        dof_pos = self.get_hand_dof_pos()
        ball_pos = self.get_ball_pos()
        ball_quat = self.get_ball_quat()  # (N, 4) w-first

        dof_vel = (dof_pos - state.info.get("prev_dof_pos", dof_pos)) / self._cfg.ctrl_dt
        ball_linvel = (ball_pos - state.info.get("prev_ball_pos", ball_pos)) / self._cfg.ctrl_dt

        # Angular velocity from quaternion finite difference:
        #   angdiff = quat_to_axis_angle(q_curr * conjugate(q_prev))
        #   angvel  = angdiff / dt
        prev_ball_quat = state.info.get("prev_ball_quat", ball_quat)
        rel_quat = np_quat_mul(ball_quat, np_quat_conjugate(prev_ball_quat))
        ball_angvel = np_quat_to_axis_angle(rel_quat) / self._cfg.ctrl_dt

        state.info["prev_dof_pos"] = dof_pos.copy()
        state.info["prev_ball_pos"] = ball_pos.copy()
        state.info["prev_ball_quat"] = ball_quat.copy()

        # Compute PD torques: torque = Kp * (target - pos) - Kd * vel
        targets = state.info["prev_ctrl"]
        p_gain = self._cfg.control_config.kp
        d_gain = self._cfg.control_config.kd
        torques = p_gain * (targets - dof_pos) - d_gain * dof_vel
        torques = np.clip(torques, -0.5, 0.5)

        terminated = ball_pos[:, 2] < self._reward_cfg.reset_z_threshold

        reward = self._compute_reward(
            state.info, dof_pos, dof_vel, ball_pos, ball_linvel, ball_angvel, torques, terminated
        )
        obs = self._compute_obs(state.info, dof_pos, ball_pos)
        return state.replace(obs=obs, reward=reward, terminated=terminated)

    def _compute_reward(
        self, info, dof_pos, dof_vel, ball_pos, ball_linvel, ball_angvel, torques, terminated
    ) -> np.ndarray:
        dtype = get_global_dtype()
        reward = np.zeros(self._num_envs, dtype=dtype)
        step_count = info.get("steps", np.zeros(self._num_envs, dtype=np.uint32))
        should_log = self._enable_reward_log and (int(step_count[0]) % 4 == 0)
        log = {} if should_log else info.get("log", {})

        for name, scale in self._reward_cfg.scales.items():
            if scale == 0 or name not in self._reward_fns:
                continue
            rew = self._reward_fns[name](
                info, dof_pos, dof_vel, ball_pos, ball_linvel, ball_angvel, torques, terminated
            )
            weighted_rew = rew * scale
            reward += weighted_rew
            if should_log:
                log[f"reward/{name}"] = float(np.mean(weighted_rew))

        if should_log:
            log["reward/total"] = float(np.mean(reward))

        info["log"] = log
        return reward * self._cfg.ctrl_dt

    def _compute_obs(self, info, dof_pos, ball_pos) -> dict[str, np.ndarray]:
        dtype = get_global_dtype()
        targets = info["prev_ctrl"]
        dof_pos_norm = 2.0 * (dof_pos - self._dof_mid) / (self._dof_range + 1e-8)

        noise_cfg = self._cfg.noise_config
        if noise_cfg.level > 0.0:
            dof_pos_norm += (
                np.random.uniform(-1.0, 1.0, dof_pos_norm.shape).astype(dtype)
                * noise_cfg.level
                * noise_cfg.scale_joint_angle
            )

        current_obs = np.concatenate(
            [dof_pos_norm, targets, ball_pos.astype(dtype)], axis=1, dtype=dtype
        )  # (N, 35)

        num_envs = dof_pos.shape[0]
        obs_lag_history = info.get(
            "obs_lag_history",
            np.zeros(
                (num_envs, self._NUM_LAG_STEPS, self._NUM_OBS_PER_STEP),
                dtype=dtype,
            ),
        )
        obs_lag_history[:, :-1] = obs_lag_history[:, 1:]
        obs_lag_history[:, -1] = current_obs
        info["obs_lag_history"] = obs_lag_history

        return {
            "obs": np.asarray(obs_lag_history.reshape(num_envs, -1), dtype=dtype),
        }
